version: '3.8'

services:
  web:
    build: /home/ubuntu/acik-kaynak-yazilim/dockerodev
    command: python3 wordApi.py -h 0.0.0.0
    volumes:
      - /home/ubuntu/acik-kaynak-yazilim/dockerodev/:/usr/src/app/
    ports:
      - 5001:8800
